### PR TITLE
Fix CSS asset handling

### PR DESCRIPTION
**Pull request by auggod**
This fixes issue with css not working in production.

I replaced undefined `entry` with `app.entry`. I think, that's all.

### CODE REVIEW

**Comment by tornqvist** [comment]
Good catch! But actually I think it should be `entry || app.entry`. Because if jalla is supplied with the `--css` option, that will be assigned to `entry`. If there's no explicit css entry point, we use `app.entry` as a proxy.

**Comment by auggod** [comment]
Right, I was not sure about this yet.
I've missed `bundle:script` event and this line `if (file !== app.entry) return`. Modified the code using `entry || app.entry` as you mentioned. I confirm it works now using `--css`.

**Comment by tornqvist** [comment]
Yeah, the code could be better documented. There are a lot of changes going on in the `build` branch (published as `jalla@experimental-build`) and with that I hope to clean up some code as well.

Anyway, thanks for the fix!

**Comment by tornqvist** [comment]
v0.11.2 🎉

**Pull request merged**
